site_name: EZReplicator
site_url: https://bhristt.github.io/EZReplicator
repo_name: bhristt/EZReplicator
repo_url: https://github.com/bhristt/EZReplicator

theme:
  name: material
  palette:
    primary: "Deep Purple"
    accent: "Deep Purple"

nav:
  - Home: index.md
  - Tutorial:
    - Getting started: tutorial/getting_started.md
    - Basic Subscription usage: tutorial/subscriptions.md
    - Other usage: tutorial/other_usage.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences