site_name: EZReplicator
site_url: https://bhristt.github.io/EZReplicator
repo_name: bhristt/EZReplicator
repo_url: https://github.com/bhristt/EZReplicator

theme:
  name: material
  palette:
    primary: "Red"
    accent: "Red"

nav:
  - Home: index.md
  - Tutorial:
    - Getting Started: tutorial/getting_started.md
    - Basic Subscription Usage: tutorial/subscriptions.md
    - Replicator Signals: tutorial/signals.md
    - Replicator Requests: tutorial/requests.md
    - Advanced Subscription Usage: tutorial/advanced_subscriptions.md
  - API: api.md

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences